name: Tests

on: pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        sudo apt install poppler-utils tesseract-ocr
        python -m pip install --upgrade pip
        pip install poetry
    - name: Setup Project
      run: |
            poetry install --with dev
    - name: Run tests
      run: poetry run pytest
